micronaut:
  application:
    name: training-micronaut
datasources:
  default:
    url: jdbc:mysql://192.168.31.151:3306/training
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: MYSQL
